### ISSUE TITLE
Booking: Clear date filter when past that date 

### ISSUE THREAD

**Issue by maxlk96** [Vatsim-Scandinavia/controlcenter#1053]
When opening CC bookings page, it saves the filters I've set to show the same one's next time I open the page, which is convenient.

When that date has passed, it would be great if the date filter gets reset/forgets the filter, as it does not show booking lying in history.

**Comment by blt950** [comment]
To my knowledge that is not possible to do with the table dependency we use. Question is if we should in general highlight today's bookings somehow? Like a tiny bit yellow background or something on those?

**Comment by blt950** [comment]
I just recalled that filter save function is a "feature" rather than a "bug". The main purpose was that if you filter you FIR, you don't need to select FIR each time you open bookings 😄 Though I'll add the "today" highlight as I think that would be useful regardless

**Comment by blt950** [comment]
The solution was to replace the date with "Today" text. This will also help if your browser saves the filter, so next day you open bookings, it'd show today's bookings as well - partially resolving the original issue.

This will be available in the next update.
