### ISSUE TITLE
Does fast track re-assign mentor on completion?

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/controlcenter#1060]
> Skjedde noe utrolig snodig når jeg satte trening 3532 som completed. Linus ble satt som mentor på nytt og det gikk ut e-post på det.

Worth a check in test if there's a quirk here. Perhaps check if there are other completed trainings out there with a mentor assigned.

**Comment by Atriusftw** [comment]
This has also happened on a refresh training (See training ID 3983 in VATSCA Prod).

**Comment by Atriusftw** [comment]
This has also happened with a training of type Transfer. See 3614 in VATSCA Prod.

**Comment by blt950** [comment]
I've checked the code and tried to reproduce it. The only thing I can grasp with the log timestamps and current logic, is that the save button was hit twice. I've added a spinner there now to avoid this happening. If it happens again after the update releases, feel free to re-open this issue.
