### ISSUE TITLE
Notification template for completed training

### ISSUE THREAD

**Issue by Atriusftw** [Vatsim-Scandinavia/controlcenter#1061]
**Is your feature request related to a problem? Please describe.**
Having to manually send relevant information to students that completed their training.

**Describe the solution you'd like**
A notification template in CC that we can update on-demand with useful information. Ideally possible to use jinja templating or similar to create cases with different information per rating or training type.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by blt950** [comment]
Thanks. This is currently not planned, but I'm leaving this open if someone wants to contribute or pick up this request.

**Comment by blt950** [comment]
Whops, refered wrong issue.

**Comment by blt950** [comment]
I had a look at this and the logic is a bit too complex for the current simplistic templating we do. What we already do today is give a link to feedback form.
`$textLines[] = 'Could we ask for a moment of your time to [share your thoughts and experiences about your training](' . $feedback . ')? Any insights you can provide would be greatly appreciated and will help us improve our training.';`

A half solution here is that we could create a "here's a link to useful information now that you're training is completed". Then I can set that per area, e.g. it could be a link to wiki? Would that fill the need?

**Comment by Atriusftw** [comment]
> I had a look at this and the logic is a bit too complex for the current simplistic templating we do. What we already do today is give a link to feedback form. `$textLines[] = 'Could we ask for a moment of your time to [share your thoughts and experiences about your training](' . $feedback . ')? Any insights you can provide would be greatly appreciated and will help us improve our training.';`
> 
> A half solution here is that we could create a "here's a link to useful information now that you're training is completed". Then I can set that per area, e.g. it could be a link to wiki? Would that fill the need?

Would be nice to get information about the wiki page for [new controllers](https://wiki.vatsim-scandinavia.org/books/operating-procedures/page/getting-started-as-a-new-controller) atleast.
