### ISSUE TITLE
VATSIM_CORE_API_TOKEN Env Variable not being properly read.

### ISSUE THREAD

**Issue by hatoriganzo** [Vatsim-Scandinavia/controlcenter#1081]
**Environment**
CC Version: ghcr.io/vatsim-scandinavia/control-center:v4
Host type: Docker Compose running on Portainer

**Describe the bug**
VATSIM API V2 token is not being read when configured per documentation as the VATSIM_CORE_API_TOKEN environment variable in the dockercompose.yml.

**How to reproduce**
1. Set VATSIM_CORE_API_TOKEN to a valid (Tested via Postman) API Core V2 Token.
2. Navigate to /users
3. Get _Error fetching users from VATSIM API. Check if your token is correct_ error message.

**Expected behavior**
Working user page

**Screenshots**
<img width="687" alt="image" src="https://github.com/user-attachments/assets/1b69faf3-728f-4324-b059-e559d425b9ee">

**Additional context**
After some tracking, I noted the config variable is being assigned in config/vatsim.php line 15.

```php
'core_api_token' => env('VATSIM_CORE_API_TOKEN', null),
```
Running php artisan tinker in the container I noticed the ENV variable is properly set but the config property stays null. Works with other variables assigned the same way tho.
<img width="542" alt="image" src="https://github.com/user-attachments/assets/8dced863-885e-48fa-8b08-29c9b60eaba2">

**Comment by blt950** [comment]
Sorry, but I can't give you support on almost year old version (v4) when v6 is now the current one.

**Comment by hatoriganzo** [comment]
Oh! (Might want to update the docs :P) Updating.

And yeah, the variable name changed that's why.

**Comment by blt950** [comment]
Can you link me to the docs where it told you to update to v4? I'll correct it

**Comment by hatoriganzo** [comment]
Sure! It's on the following pages:

https://docs.vatsca.org/controlcenter/latest/getting-started/ 
In the example docker-compose.yml

https://docs.vatsca.org/controlcenter/latest/installation/
Open up a terminal and pull the latest image with:
docker pull ghcr.io/vatsim-scandinavia/control-center:v4

**Comment by hatoriganzo** [comment]
<img width="720" alt="image" src="https://github.com/user-attachments/assets/5081c8a7-265c-4a79-9884-3147f9d34de8">

Unfortunately, I'm still having issues with my API Key (Updated to V6.06). Although now the config is getting set correctly.

<img width="395" alt="image" src="https://github.com/user-attachments/assets/14cfb919-f751-4ea9-adbc-5706fcf174de">

**Comment by bedrich-schindler** [comment]
If `VATSIM_CORE_API_TOKEN` is correctly set in `.env` file, try to call `php artisan key:generate`.

**Comment by hatoriganzo** [comment]
Ran both commands inside the container but the issue remains.

**Comment by blt950** [comment]
I don't understand why this wouldn't work for you unless the key is actually invalid or maybe an v1 key. Everything works on my end here. 

Confirm this key of yours can be called in the `https://api.vatsim.net/v2/` API successfully?

**Comment by bedrich-schindler** [comment]
I personally do not use Docker on production, but what about this? https://docs.vatsca.org/controlcenter/latest/getting-started/#add-the-docker-compose-file. Environment is specified in docker-compose file in this example. I do not know how @hatoriganzo configured CC, but can't be this problem? You can also specify .env file using https://docs.docker.com/compose/how-tos/environment-variables/set-environment-variables/#use-the-env_file-attribute

But I am just guessing and throwing some stuff that came up to my mind

**Comment by bedrich-schindler** [comment]
Also, @hatoriganzo, did you check that you have latest image? From my experience, sometimes  I must explicitly rebuild the image otherwise old tag is installed (v4 instead v6). Something like `docker compose --build --no-cache ...`

**Comment by blt950** [comment]
Since @hatoriganzo already did tinker and `vatsim.core_api_token` and got back his key, I'd assume the key itself is available.
For checking the version, look at the bottom left in sidebar.

**Comment by hatoriganzo** [comment]
Yeah I'm starting to think the key is the issue. It was just given to me from the dev team but I'll inquiry with them. Do you know any endpoint in the API that REQUIRES the key so I can properly test?

**Comment by blt950** [comment]
https://vatsim.dev/api/core-api/orgs-api-subdivision-roster

**Comment by hatoriganzo** [comment]
Oh this is amazing. My key is not wrong, it just breaks the Vatsim code? Hahaha if I try with an invalid key I get.

Status 403 Forbidden
"message": "permission_denied"

If I try with my key.. it breaks
<img width="987" alt="image" src="https://github.com/user-attachments/assets/710b67a9-1b4f-43f3-9f12-834e6cf5b692">

**Comment by hatoriganzo** [comment]
Yeah, it's working :c

<img width="533" alt="image" src="https://github.com/user-attachments/assets/ce881a0e-0836-476b-a7a2-f71b53289d4f">

**Comment by blt950** [comment]
I found out why.. Because the API calls the subdivision call instead of division😅😅

https://github.com/Vatsim-Scandinavia/controlcenter/blob/4c52b193b14ee72bc2e524eaf5735ad125837329/app/Http/Controllers/UserController.php#L440

If you change this to the division call instead?

**Comment by hatoriganzo** [comment]
Changed the code and. 🥁 

It worked

**Comment by hatoriganzo** [comment]
Marking as closed as related to #1080.
