### ISSUE TITLE
Possible to upload multiple reports with same ontime link

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/controlcenter#1085]
**Environment**
CC Version: v6.0.6

**Describe the bug**
Last two times I have had an exam, the uploading of result from a onetime link is surprisingly slow and with no indication that its being processed. Clicking the button multiple times will result in the same report being sent again and again. Once the page actually loads, you can find multiple report being uploaded.

Idk if this is related to onetime links itself or the upload report functionality - however I have only been working with these via onetime links.

**How to reproduce**
Upload a report as examiner via onetime link
Press the green button to upload
Be impatient and press it again
and again

Now you have 3 reports!

**Expected behavior**
That a onetime link will only be able to generate 1 report.

**Screenshots**
![image](https://github.com/user-attachments/assets/30b30a50-0d09-4621-bdcf-9014ccf33b66)

**Device and browser (if applicable):**
Happend to be twice, both in chromium based browser - today in with Edge.

**Additional context**
A solution could be to "grey" the button out and have a loading spinning icon showing once you have pressed the button and its being processed?

**Comment by Atriusftw** [comment]
As the entire form is submitted multiple times, this also leads to multiple rating upgrade tasks in case that is requested.

**Comment by blt950** [comment]
Interesting. We haven't really changed anything in this functionality lately, but we've experienced general slowness on the website which could lead to longer upload times.

Either way, I guess a spinner could at least not give you the option of resubmitting the form again and again.
