### ISSUE TITLE
One-time link for reports gives 403

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/controlcenter#263]
Not sure, but something restricts the user who per policy is allowed to make one, to create one. It stops with an 403 Forbidden.

**Comment by blt950** [comment]
Can't seem to be reproduce in v2.0.1 anymore. I guess it "fixed itself"

**Comment by blt950** [comment]
It didn't fix it self. Still 403 for Krister and training https://cc.vatsim-scandinavia.org/training/1242
![image](https://user-images.githubusercontent.com/2505044/111226486-7f037180-85e1-11eb-80ea-0ea6b29dddd0.png)

**Comment by gustavkauman** [comment]
Hmmm it could be that it's not setting the type correctly. That would cause a check for `isModeratorOrAbove()` which would fail for Krister. But I don't understand that he'd even have the button.
@blt950 Do you know if this is still an issue?

**Comment by blt950** [comment]
The policy if you can create a OneTime link should be the same policy it checks when showing the button? Afaik he does have the button.
![image](https://user-images.githubusercontent.com/2505044/111809651-807cb480-88d5-11eb-93ea-c66d2a1e9758.png)
Attached screenshot on how it looks at his end
 @gustavkauman
