### ISSUE TITLE
ATC Hours not correct from API

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/controlcenter#293]
Adrian B. reported that his ATC hours are not correct. CC says 179, which is 200 less than status.vatsim.net

**Comment by blt950** [comment]
A tip here @gustavkauman is that VATSIM SSO closes at end of march. And there has been hints that stats.vatsim.net will be replaced as well instead of converting it into VATSIM Connect. Perhaps this new status site will show correct numbers as it'll probably use the same data. If the numbers still mismatch, then it'll indicate a fault in the API or our calculations.

**Comment by gustavkauman** [comment]
They actually reported that it was an issue inside FSD. The thread is here:
https://forums.vatsim.net/topic/29701-missing-controller-sessions-in-atcsessions-api-call/

**Comment by blt950** [comment]
Adding this to on-hold and unprioritised list until it's fixed outside our control.

**Comment by gustavkauman** [comment]
This was fixed in version 2.2.3 (PR #326). There's still a small (percent wise) discrepancy between us and stats.vatsim.net, but this is due to the values given in the API versus the ones coming directly from the VATSIM database (which stats.vatsim.net uses).

Closing this.
