### ISSUE TITLE
UpdateAtcActiveStatus Raw SQL Query Doesn't Account for Handover DB Prefix

### ISSUE THREAD

**Issue by tszczypinski6** [Vatsim-Scandinavia/controlcenter#301]
The SQL query does not account for the prefix set in the .env file, and as such the job fails as the table is not found.

It may be worth glancing over any other raw SQL queries to be sure they account for prefixes.

**Affected File(s):** app/Console/Commands/UpdateAtcActiveStatus.php
**Affected Line(s):** 69

![](https://i.imgur.com/I4e9zQi.png)

**Comment by devHazz** [comment]
I'll be pushing a fix for this within the next few minutes.

**Comment by devHazz** [comment]
Fixed in #303

**Comment by devHazz** [comment]
Fixed again in #304
