### ISSUE TITLE
Hard-Coded Scandinavia References

### ISSUE THREAD

**Issue by tszczypinski6** [Vatsim-Scandinavia/controlcenter#302]
There are still some hard-coded Scandinavia references in the "Request Training" dashboard box that should be removed and filled in dynamically.

**Affected File(s):**app/Policies/TrainingPolicy.php

![](https://i.imgur.com/McSxz65.png)

**Comment by devHazz** [comment]
I'm looking to add another definable variable in env as division name. Meanwhile, could it maybe be defined as a Global Setting?

**Comment by tszczypinski6** [comment]
This is already in there; usually APP_OWNER is the division/subdivision name, the short owner version is the division/subdivision name in CERT.

**Comment by devHazz** [comment]
Ah I did see that, I thought not too greatly of that since people might not think of it truly as a div name and just put something random. I'll push something soon.

**Comment by devHazz** [comment]
Fixed in #304
