### ISSUE TITLE
Possible access bug? - Administration > Notification Templates

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/controlcenter#379]
During the walkthough of CC with our new staff member today, he seemed to have access to other countries (including his assigned one) under notification templates. Is this by design?

**Comment by blt950** [comment]
It's by design, so you can see what others have written and get inspired or whatever. 

Did he have access to save the notifications? If yes then it'd be a bug

**Comment by Adrian2k** [comment]
Not sure.

Maybe it should default to the area you have been assigned then?

**Comment by blt950** [comment]
I've ran a test, it's view-only for the other countries you don't have access to. As this is a very rare setting you touch, we'll not put in the work to make it show the user's area by default.
