### ISSUE TITLE
Table filtering not working

### ISSUE THREAD

**Issue by aleksae** [Vatsim-Scandinavia/controlcenter#445]
Whenever there is an icon in cells, filter for that column doesn't work.

**Comment by blt950** [comment]
@aleksae Thanks for the report. Often it's missing a tag-stripper function we use, which then causes  filter to break. 

If you could come with examples of exactly which tables this applies to, I'll be easier for us to find the exact issue. Thanks

**Comment by aleksae** [comment]
@blt950 In VATSIM Adria, we first noticed it on the active members page. I wanted to check tables on your cc to be sure if it's something I changed in the code, but found same issue there (on the tables that I can access). Specifically: Training endorsements - both status and type, MA/SC Endorsements - all columns except member, Open request - type. Hope this helps.

**Comment by blt950** [comment]
I've looked a bit into the issue, it's something with the icons indeed, but also the amount of table rows. Smaller tables with few rows work fine, but once they get a lot of rows it starts breaking.

Not sure how to fix it, but feel free to PR if you find any fix :)

**Comment by blt950** [comment]
Seems I found the issue, most probably a bug from the table provider. Should be working again in CC v3.2.0 when released
