### ISSUE TITLE
Feature Request: Make a switch to select how to make an user active again

### ISSUE THREAD

**Issue by mferraroni** [Vatsim-Scandinavia/controlcenter#490]
Hello, 
v.3.3.0 had a quite drastic change: "Only a completed training closure will make a user active again", can you make this behaviour configurable so either it will be "permanently disabled until next completed training" either will be re-enabled automatically?

Context:
In vACC italy we are using that flag as a "Training Eligible" more than "ATC Active" and a controller becomes "training eligible" again after he/she controls for the minimum requirement hours.

Thanks!
Matteo Ferraroni

**Comment by blt950** [comment]
Hi @mferraroni 

Adding an button or similar to make an user ATC again again could be added. It wouldn't be a bit against it's purpose in our vACC, so it'd need to be a configurable functionality.

Question 1 then is
1. Should the button only be available for Moderator & Admins if enabled in settings
2. or; should the button only be available for Admins without setting configurability

Question 2, is a button to make someone active again enough, or two-way? Making someone active and then inactive again?

**Comment by mferraroni** [comment]
Hi @blt950 
I didn't ask for a button to make an ATC active again but a setting to either keep the behaviour pre-3.3.0 (re-enable ATC automatically if they meet the hours) either change the behaviour (permanently disable ATC until a new training is completed).
Does it make sense?

**Comment by blt950** [comment]
@mferraroni 
If I understand you correctly, you request to choose between the previous v.3.3.0 behaviour and new behaviour as setting? 

The new behaviour is already that they're disabled until a training is set completed (typically a refresh training).

**Comment by mferraroni** [comment]
yes, that's correct.

**Comment by blt950** [comment]
@mferraroni The new ATC activity checker is completely rewritten, but it should perhaps not be that hard for us to add a functionality to re-activate users that have more hours than the minimum requirement.

I'll look if we can get this in the next upcoming update :)

**Comment by blt950** [comment]
This will be released in v.3.4.0 :)

**Comment by blt950** [comment]
@mferraroni It's now released https://github.com/Vatsim-Scandinavia/controlcenter/releases

**Comment by mferraroni** [comment]
Thanks a ton @thor :-)
