### ISSUE TITLE
unalbe to enter texi in booking Position filed on firefox mobile android version 110.0.1

### ISSUE THREAD

**Issue by meltinglava** [Vatsim-Scandinavia/controlcenter#495]

**Comment by bjerrecs** [comment]
I don't have access to a 'real' android device but I have some emulation software.
Here I have downloaded Version 110.1.0 and am unable to reproduce the error
![image](https://user-images.githubusercontent.com/32055984/224232523-b4182e76-a4f2-40d7-84e5-b4bba150076c.png)
![image](https://user-images.githubusercontent.com/32055984/224232538-7e309b93-17a9-4d48-a463-cf80887d3dbc.png)
@meltinglava Can you try and update firefox and try again?

If this does not work, please provide the information about your device

**Comment by meltinglava** [comment]
Looks mike it is fixed.
