### ISSUE TITLE
User list should be based on division data

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/controlcenter#510]
The user list today is just a list over all users logged into Handover. When we'll not list that anymore, we should rather fetch the member list from VATSIM and populate with that instead. Then we could have a column saying if they've logged into CC.

Also a setting to show this list to everyone should be present. As some VACCs might use this as a roster, and some don't.

**Comment by blt950** [comment]
Also add a filter option for I3 in this list, that is missing today

**Comment by sarantos92** [comment]
if we fetch the data from vatsim we should exclude INA and SUSP its a lot of data there... no need to populate our databases ;)

**Comment by blt950** [comment]
> if we fetch the data from vatsim we should exclude INA and SUSP its a lot of data there... no need to populate our databases ;)

I agree, though I don't think we'll save this data at all. We'll just call the API and render it in the view instead. Though I'll see if there's some way to exclude ratings that don't really apply, but I can't recall that being a parameter in the API.
