### ISSUE TITLE
Controller Feedback

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/controlcenter#511]
Would be nice to include controller feedback in CC. Would require SSO login for us to be allowed to show full names of the controller you want to give feedback on. Then we could also send the feedback directly to the controller and the staff.

Example from Hellenic VACC
![image](https://user-images.githubusercontent.com/2505044/234358505-933531a2-21b3-4182-af3e-7e1d1637eae7.png)

**Comment by blt950** [comment]
See #375 for perhaps having a workflow instead of sending directly to student.

**Comment by SpyrosTTK** [comment]
We will be transitioning to CC by the end of summer as well. We would love this type of feedback to be included!
