### ISSUE TITLE
Mobile buttons are a bit oversized

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/controlcenter#549]
The CTA's on mobile are a bit oversized. Perhaps on mobile we should only have an icon or try to find a bit shorter words as it's breaking into two lines etc.

**Comment by blt950** [comment]
Perhaps not mobile only issue, rather that the card heading is on two lines


![Image](https://github.com/Vatsim-Scandinavia/controlcenter/assets/2505044/2188fbfc-4915-4350-8f2c-8796a9cd9eca)

**Comment by thor** [comment]
Did #555 fix it or contribute to it?

**Comment by blt950** [comment]
Fixed in #555
