### ISSUE TITLE
Enable theming in v4

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/controlcenter#552]
So if you change the border-radius env, it requires a new npm build. Since the container doesn't have node installed, it can't really be rebuilt with the new variables. Is there any good ways to solve this @thor ?

Same for rest of theme options, they need a re-run of npm

**Comment by thor** [comment]
Ack. 🤔 The _cleanest_ way here would probably be for users to rebuild the local styles and bind them into the container, at least if they want to make them over time. 

Alternatively, users need to create their own `Dockerfile` with a `FROM` that points to our container and then set those environment variables in it. That'll result in a clean container with the style as wanted.

**Comment by blt950** [comment]
Alternative with Dockerfile with FROM seems to be the most clean. Smells `THEMING.md` documentation for that sort.

**Comment by blt950** [comment]
Alright, so I tested this a bit in a smaller scale in the upcoming Handover update. I was sniffing at the Dockerfile FROM solution but concluded this is too advanced for our users who are very new to docker.

So I compromised a bit the concept of leaving the container alone for the user friendlyness of theming with just a simple command. This command installs npm in the container, builds the image and removes npm again. This ends up with only increasing the container size with ~200mb instead of ~1GB if we kept the files after build.

Only downside, but liveable is that you need to do this each time you recreate the container.
See https://github.com/Vatsim-Scandinavia/handover/pull/79 for details.

If you're happy with this solution as well @thor , we can add it to Control Center as well.
