### ISSUE TITLE
Notify admins if running outdated CC version

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/controlcenter#554]
To push people to have correct configurations and settings, I suggest for admins:
- [ ] Notification banner that a new version is out

**Comment by thor** [comment]
Re: failsafe the check could validate if a date column hasn't been updated as expected, or check a flat file or similarly.

**Comment by blt950** [comment]
We could also use https://api.github.com/repos/Vatsim-Scandinavia/controlcenter/releases to fetch if there's a new release out. Check if first entry is not equal the current running version -> a new update is available!

**Comment by blt950** [comment]
Agree @thor , we could just get some simple column or row of some sort to update with a date if cronjob has ran. We could put it into the "Setting" things, so it also could be displayed in admin settings.
