### ISSUE TITLE
Small typos

### ISSUE THREAD

**Issue by mjpikat** [Vatsim-Scandinavia/controlcenter#565]
1. ‎resources/views/usersettings.blade.php change myVatsim to **myVATSIM**
2. resources/views/training/exam/create.blade.php change Vatsim ID to **VATSIM CID**
3. resources/views/training/show.blade.php change Vatsim ID to **VATSIM CID**

Priority: low

**Comment by blt950** [comment]
Thanks, I've sorted out #1.
2 and 3 are more potato potato thing.
