### ISSUE TITLE
Timeline comment edits not working

### ISSUE THREAD

**Issue by pietikainen** [Vatsim-Scandinavia/controlcenter#570]
The pencil button doesn't open the edit textbox or do anything. :3

**Comment by thor** [comment]
Hi @pietikainen! To confirm, nothing happens when you use the pencil associated with a timeline comment?

Could you help me out with the browser you're using? In case it's a browser-specific problem, it'll help during troubleshooting.

**Comment by blt950** [comment]
@pietikainen Could you click edit and send a screenshot here of your whole screen? Could give some pointers on what's going on. Also a screenshot of your web development console: https://help.vivaldi.com/desktop/tools/developer-tools/ (Open it and choose console)

**Comment by blt950** [comment]
As we haven't heard back for 3 weeks I'm closing the issue. I've however made the edit button highlight the input field where you are supposed to edit, since I would image some users won't see that you need to look back up to edit the text rather than in-field of where you clicked.
