### ISSUE TITLE
API endpoints for endorsements does not return last name

### ISSUE THREAD

**Issue by bedrich-schindler** [Vatsim-Scandinavia/controlcenter#595]
For purpose of ATC rooster (#594) and list of all endorsements, we need to have last names returned by endorsements endpoints. While the last name is already returned by booking endpoints, I think we can return them also there.

**Comment by blt950** [comment]
So if I understand correctly, you all of these endpoints to output the full name of the user?
- /endorsements/visiting
- /endorsements/examiner
- /endorsements/training/solo
- /endorsements/training/s1
- /endorsements/masc

**Comment by bedrich-schindler** [comment]
Yes, if it is possible. While bookings API returns it as well, I would expect it also here. (We do not expect to enlist names publicly, but it is nice to have for logged users).

**Comment by blt950** [comment]
Won't be necessary anymore due to #594
