### ISSUE TITLE
Installation steps for docker, hard to understand without experience

### ISSUE THREAD

**Issue by cptalpdeniz** [Vatsim-Scandinavia/controlcenter#599]
Hello,

Can the installation steps be made little bit clearer for the automatic installation? For someone who never used docker or any packaging container etc (web is not even area of focus) this is very hard to understand.

1. ✔️ Was able to pull the image using `docker image pull ghcr.io/vatsim-scandinavia/control-center:v4`.
2. ✔️ Created a new database on MySQL.
3. ❌ "Configure the environment variables as described in the CONFIGURE.md", do I need to edit a file (like a `.env` file)? What does it mean by configuring the environment variables
4. ❌ "Start the container in the background." how to do this?

Thank you

**Comment by blt950** [comment]
Hello there 👋🏻 

Docker is perhaps not the easiest way if you've limited experience with web development. I would recommend to see some of many guides out there on the internet on how to setup a docker container, but let me elaborate those steps that are related to Control Center specifically:

3. You're onto it, .env file is the file inside the container. Though we recommend to use the environment variables provided through the container itself as it's easier to change and not prone to wipe upon updates.
4. I think at this and actually previous step, it'd be easier for you to use `docker compose` in the root folder of the project itself. Check out the `docker-compose.yaml` file, tweak the files to your settings and use `docker compose up -d` command. Then the container will be configured correctly (step 3) and ran in the background (step 4)

**Comment by cptalpdeniz** [comment]
Hello Daniel,

Thank you very much for your prompt response. 

3. I will check what is needed regarding passing environment variables to the docker. I posted a similar question to StackOverflow and responses I got were regarding passing a file to docker using the `-e` command and running `docker run` command however this doesn't seem to be aligning with what you are saying, editing the `.env` file inside the container. My main issue is I cannot find where the container is or where it is downloaded since there is no `/var/lib/docker/` even though `docker info` says the storage is driver is `overlay2`
4. I will check the file and tweak things. Another question is, let's say I tweaked this file, do I just pass it as an argument to the compose command? 

Thank you

**Comment by blt950** [comment]
Hi,

3. I'm actually unsure what you mean here. I'd just skip your step 3 and go for 4 as explained above. If you're not techy it might be useful to have a Docker GUI on your server, such as [Portainer](https://www.portainer.io/)
4. If you tweak the file you re-create the whole container again. Though if everything is setup correctly, all data will still persist when doing this.
