### ISSUE TITLE
Rounding error in training application hours

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/controlcenter#687]
When applying for a training that requires a specific amount of hours, your hours will be rounded in the front-end, but not back-end. So with 64,59 hours you'll get this validation error

![image](https://github.com/Vatsim-Scandinavia/controlcenter/assets/2505044/5257cd16-24f4-4467-851b-16aab34bded3)

This can be solved by showing at least one decimal or rounding down in: https://github.com/Vatsim-Scandinavia/controlcenter/blob/1c1857b88a3ef202dddd4bf3c47a1fda55a077f2/resources/views/training/apply.blade.php#L199

**Comment by thor** [comment]
Hah, damnit! I was thinking of creating the same issue. _shakes fist_
