### ISSUE TITLE
release-please release author

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/controlcenter#688]
We need to solve the workflows by changing the author of the release `vatsca-bot`.
Please complete this task when it's fixed @thor

**Comment by thor** [comment]
Tried to log in but noticed the two-factor step. Seems like I'm not a member on the mailing list or mailing group, @blt950. Let me know when that's sorted. 👍

**Comment by blt950** [comment]
Any update on this one @thor ? 😊

**Comment by thor** [comment]
> Any update on this one @thor ? 😊

Besides pinging you when necessary, which I'll most likely do for this, would it be possible to get access to web@?

**Comment by blt950** [comment]
> > Any update on this one @thor ? 😊
> 
> Besides pinging you when necessary, which I'll most likely do for this, would it be possible to get access to web@?

We can take this on PM, I can give you access to web@ yea

**Comment by thor** [comment]
Could be fixed; I've updated the token to use the token from the vatsca-bot. Assuming that I successfully created the PAT, and didn't forget anything instrumental, it _should_ work. It seems to have executed, so let's find out on next release. 👀

**Comment by blt950** [comment]
Seems to work, just a note that it still publishes the release notes as draft. Is that intended @thor ?

**Comment by thor** [comment]
> Seems to work, just a note that it still publishes the release notes as draft. Is that intended @thor ?

Nah, sounds like I forgot to change that. 👍🏼
