### ISSUE TITLE
Internal GCAP Changes

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/controlcenter#692]
## Name changes

After reading the GCAP again in fine prints, the required changes in this context will be minimal. We're talking:

- [x] Rename MAE to T1 or correct Tier endorsement. This is more a local database change than code change.

### Changes to Sweden:
- T1 ESSA TWR - replaces MAE ESSA TWR
- T1 ESSA APP - replaces MAE ESSA APP
- T2 ESAA APS - new
- T2 ESAA AFIS - new
- T2 ESAA MIL - new

### Changes to Finland:
- T1 EFHK TWR - only after S2
- T1 EFHK APP - bundle with S3
- T2 EFIN R TWR - only after S2
- T2 EFIN P TWR - only after S2

Also retroactively add endorsements according to rules Otto sent me on DM

### Changes to Norway:
- T1 ENGM TWR
- T1 ENGM APP
- T2 ENOB Oceanic

### Changes to Iceland:
- T2 BIAR
- T2 AFIS
- Oceanic is deleted

Also retroactively add endorsements according to rules Kieran sent me on DM

### Changes to Denmark:
- BIDE removed completely, as we're not going any further with that endorsement.
- EKCH MAE's should be renamed as: 
  - T1 EKCH_DEL/GND (S1)
  - T1 EKCH_TWR (S2)
  - T1 EKCH_APP/DEP (S3+)
- New
  - T2 EKDK AFIS
  - T2 EKRN 
  - EKDK TWR Regional (Gives permission to sit on EKBI, EKAH, EKYT, EKSP & EKKA)

Must be implemented within 1st March 2024

## 1st of March
- [x] Enable seperate rosters setting and verify it works correctly -> run activity check to send out inactive notices
- [x] Publish the new Student/Mentor Policy
- [x] Publish NOTAM in announcements for everyone
- [x] And NOTAM in Norway
- [ ] Send a list of positions again, could be rating requirement have changed 
- [x] IMportant: For those who have S1+S2 bundles and someone drops out, you must change training to S1 and complete it so they're marked as active. Because they're active according to GCAP.
- [x] Update hour requirements
- [x] Let TA's know they can add grandfather rights after division API integration is released

**Comment by blt950** [comment]
We need some way to roster familiarisations inside VATSCA

**Comment by thor** [comment]
> https://discord.com/channels/182554696559362048/977579922765807687/1184194652186882089

<img width="529" alt="image" src="https://github.com/Vatsim-Scandinavia/controlcenter/assets/234489/4b72e319-e084-4af2-a930-25c07284a1d9">

🥲

**Comment by blt950** [comment]
Just a link to internal note in training staff chat. 

We need a way to track familiarisation training. TBH not sure what that means, hence I linked the chat for myself to investigate in the future the actual details and impact. I'll update this issue when I know.

**Comment by blt950** [comment]
Removed the notify when going inactive, this was orignally related to §9.4(c) where a subdivision chooses one of i-iii options. Hour based activity is what CC is created for and does not require a notification.

Removed the part with VATEUD DTP §3.8.5 regarding 6 months wait to apply again after failing a tier 1/2. This is so nieche that I don't see any point of implementing until it gets requested. This paragraph does not apply to standard non-tiered trainings. Hence nieche.
