### ISSUE TITLE
S1 positions in booking not tagged with event

### ISSUE THREAD

**Issue by Atriusftw** [Vatsim-Scandinavia/controlcenter#753]
![image](https://github.com/Vatsim-Scandinavia/controlcenter/assets/1478937/3aaae2f5-2a6d-4ddf-9401-a1ceb64bbb9b)

![image](https://github.com/Vatsim-Scandinavia/controlcenter/assets/1478937/330e67fc-890b-4f4a-b24a-6e39a480713c)

This has been the case for multiple events in the past as well. Not sure if this is an issue with the code or something when setting up events?

**Comment by thor** [comment]
Thanks for the report, @Atriusftw! Out of curiosity, (and laziness because I don't want to create one locally) could you tell me how you created the booking, and whether you have the choice of adding any tags if you open up the booking page in Control Center?

**Comment by blt950** [comment]
Also out of curiosity: Did this issue start from the time you opened a S2 training that's now in queue?

**Comment by Atriusftw** [comment]
@thor Via `/booking`, filling out the form on the right in the "Create Booking" form by entering Date, Start- and End time and position (e.g ENBR_DEL) then clicking the Add Booking button.

@blt950 I can't recall if this was the case before i put in my S2 training request, as i did so the week after i got my S1 rating (due to the enforced cooldown :>). The `ENBR_GND` booking in my first screenshot is by another S1 rated person. Not sure if they have a S2 request, but you could probably check that (I have sent you the CID on discord. Don't want to disclose it here even tho it isn't personal information).

**Comment by thor** [comment]
Thanks for responding, Marius! I'll try to recreate the issue.

**Comment by blt950** [comment]
I've resolved the issue while working on the related GCAP combability update. It was simply not available for S1 controllers.
