### ISSUE TITLE
Disable vote functionality

### ISSUE THREAD

**Issue by mjpikat** [Vatsim-Scandinavia/controlcenter#830]
Just like with feedback, please add the setting to disable "Votes" and related settings

**Comment by blt950** [comment]
Hello,

Could you elaborate a bit why you request this? I don't see the value of a such setting when vote creation is only available for administrators, and not visible to others unless there's an active vote running. So practically it'd only visually be one less item in "Administration" menu dropdown, which admins only can see.

**Comment by mjpikat** [comment]
That's exactly what I expect. But I guess I will just fork the repo then and "hide" this option from the dropdown.

**Comment by blt950** [comment]
Your PR with the requested functionality is very welcome @mjpikat :) Then I can push it into the official version as well and we help each other building Control Center.
