### ISSUE TITLE
Training request vue error

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/controlcenter#831]
I have observer following issue (it is happening in 5.0.4 and 5.1.0). If I go to my profile to add training type. When I choose training area, whole page crashes with TypeError: null is not an object (evaluating 'rating.id'). 

![image](https://github.com/Vatsim-Scandinavia/controlcenter/assets/2505044/a8556735-e13f-430f-8501-bf039b54a570)
![image](https://github.com/Vatsim-Scandinavia/controlcenter/assets/2505044/97dbf018-7e3e-4360-9ac9-756d9c26431f)
![image](https://github.com/Vatsim-Scandinavia/controlcenter/assets/2505044/1955d734-7718-4770-9b48-fceecb52fad3)
![image](https://github.com/Vatsim-Scandinavia/controlcenter/assets/2505044/45a269d7-84aa-44a5-a6fc-d89fee329199)

**Comment by blt950** [comment]
@bedrich-schindler ( I can't seem to tag you ),

Could you provide a screenshot of your `ratings` and `area_rating` tables? I'm not able to reproduce it and I think this is a misconfiguration issue.

**Comment by bedrich-schindler** [comment]
<img width="695" alt="image" src="https://github.com/Vatsim-Scandinavia/controlcenter/assets/10213870/06fef7ae-3276-4e83-a0fc-cb93b191397e">
<img width="1025" alt="image" src="https://github.com/Vatsim-Scandinavia/controlcenter/assets/10213870/dd7079f7-08e2-4ba3-ae6d-a2d7cd957666">

**Comment by blt950** [comment]
That's your issue then, please don't remove VATSIM Ratings :D As several places in the code helpers depend on these to display ratings correctly. E.g. if you get someone with C3 to login in CC, it should be defined in `ratings` to correctly identify them.

**Comment by bedrich-schindler** [comment]
> Here you find the diffrerent data tables which need to be edited to suit your subdivision.
> https://docs.vatsca.org/controlcenter/dev/setup/division/#ratings 

Do you think that I am only stupid guy or should I improve textation of Ratings section with wording such as  "Do not remove default VATSIM ratings"? :-D

**Comment by blt950** [comment]
I mean... It's a user error ;) But yea, it should be mentioned in the documentation. I'll add it in.
