### ISSUE TITLE
Slash isnt requied give the wrong link

### ISSUE THREAD

**Issue by sarantos92** [Vatsim-Scandinavia/controlcenter#835]
https://github.com/Vatsim-Scandinavia/controlcenter/blob/5c5b32a54f4bcd0f81cf0d26355343c0fdb0e47f/resources/views/training/show.blade.php#L749C1-L750C1

![image](https://github.com/Vatsim-Scandinavia/controlcenter/assets/64693022/76f283c1-786a-4460-af8c-4b6b88146333)

**Comment by blt950** [comment]
Thats not a bug, it's your `.env` configuration. Your `APP_URL` should not have a slash.

`APP_URL=http://cc.hvacc.org` instead of  `APP_URL=http://cc.hvacc.org/`
