### ISSUE TITLE
Add possibility for subdivision name override

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/controlcenter#840]
Today your subdivision name is based on `VAT + config APP_OWNER="SCA"`. This works well and ends up with `VATSCA`, however for Estonia (and others) who name themselves `ESTVACC` instead of `VATEST` this becomes wrong, also because the APP_OWNER is used to call the correct API's and check who can apply for trainings.

Solution suggestion:
`APP_OWNER_NAME` that overrides the name in views. If not defined, it'll revert to old `VAT+CONFIG` solution. This way this won't be a breaking change either.

**Comment by bedrich-schindler** [comment]
Thumb up for this. Just for info. Our official name is VACC Czech Republic (or VACC Czechia), short name is VACC-CZ and from VATSIM point of view, we have code CZCH.
