### ISSUE TITLE
Make "ATC Roster" a single link

### ISSUE THREAD

**Issue by mjpikat** [Vatsim-Scandinavia/controlcenter#906]
**Is your feature request related to a problem? Please describe.**
Only a feature request

**Describe the solution you'd like**
For the most of subdivisions, CC is used only with one area defined. Hence it would be a little more comfortable from UI perspective when the dropdown is just replaced with a single link to "ATC Roster".

**Describe alternatives you've considered**
Alternatively, "ATC Roster" can be hidden AND/OR simply point to "Endorsements - Facility" page.

**Additional context**
Possible option:
![Screenshot 2024-04-21 at 14 46 38](https://github.com/Vatsim-Scandinavia/controlcenter/assets/8924515/048805a6-9922-4efd-a5ce-bad3cd835175)

**Comment by blt950** [comment]
I agree, I'll see to fix this in a future update. Thanks for your suggestion.
