### ISSUE TITLE
Links to VATEUD Core Profile gives 401

### ISSUE THREAD

**Issue by Atriusftw** [Vatsim-Scandinavia/controlcenter#907]
**Environment**
CC Version: v5.2.5
Host type: N/A

**Describe the bug**
Clicking the links to VATEUD Profile uses a link that isn't available, and gives a 401 error.
I've found this link under `/user` and `/training` so far.

**How to reproduce**
1. Go to cc.vatsim-scandinavia.org
2. Click on your name in the top right corner
4. Hover over your CID under User Details
5. Click the globe to navigate to your VATEUD Profile
5. See error

**Expected behavior**
It is expected to see your VATEUD profile.

**Screenshots**

![image](https://github.com/Vatsim-Scandinavia/controlcenter/assets/1478937/81d482ec-2bf9-4370-bb63-8802ac06a866)

**Additional context**
Used link is `https://core.vateud.net/manage/controller/<cid>/view`. Expected URL is probably `https://core.vateud.net/my/profile`.

**Comment by blt950** [comment]
Thanks for the report. This seems more like a shortcut that you as user/mentor should not be able to see, as the link is only accessible by training staff in EUD Core. 

Changing it to `https://core.vateud.net/my/profile` will be incorrect as it's not the same type of page. I think I'll just fix so the link is only visible to relevant users.
