### ISSUE TITLE
Expired endorsement shows as active on the user profile

### ISSUE THREAD

**Issue by Atriusftw** [Vatsim-Scandinavia/controlcenter#917]
**Environment**
CC Version: 5.2.5
Host type: ?

**Describe the bug**
Expired endorsement shows as active on the user profile. This was for ID 1507575.

**How to reproduce**
1. Go to `/endorsements/solos`.
2. Search for the user ID.
3. See that the endorsement granted 09/06 is expired.
4. Go to the user profile.
5. See that the endorsement there is still active.

**Expected behavior**
Expect endorsements to be in sync

**Screenshots**
These screenshots were taken same day at 12:23z

![image](https://github.com/Vatsim-Scandinavia/controlcenter/assets/1478937/f420f61b-68dc-42f5-a546-46eb05b81939)
![image](https://github.com/Vatsim-Scandinavia/controlcenter/assets/1478937/255e743f-044b-4e1c-85b4-f9c80b655539)

**Comment by blt950** [comment]
This seemed to have happened because VATSCA VPS stopped running the cronjobs for some reason. It should be resolved now. Let me know if the issue persists.
