### ISSUE TITLE
Add entry for new training reports under activities

### ISSUE THREAD

**Issue by Atriusftw** [Vatsim-Scandinavia/controlcenter#918]
**Is your feature request related to a problem? Please describe.**
To get a better overview on the ongoing training activity it would be nice to have entries in `/reports/activities` when mentors add new training or exam reports.

**Describe the solution you'd like**
As described above, add a new entry when a training or exam report is added to a training.

**Describe alternatives you've considered**
Alternative is to watch `/reports/mentors`, open the training from there and open the report.

**Comment by blt950** [comment]
Thanks for the suggestion. I'll add it to our list.
