### ISSUE TITLE
ATC Roster table filtering displays "Visiting" option incorrectly

### ISSUE THREAD

**Issue by romtam** [Vatsim-Scandinavia/controlcenter#945]
**Environment**
CC Version: 5.3.1
Host type: N/A (https://cc.vatsim-scandinavia.org/)

**Describe the bug**
In ATC Roster pages with visiting controllers, the table filter in the ATC Active column shows "Visiting Visiting" instead of "Visiting".

The bug only affects the filtering dropdown, the filtering itself works as intended.

**How to reproduce**
1. Go to an ATC roster page with visiting controllers ([Iceland](https://cc.vatsim-scandinavia.org/roster/3) and [Sweden](https://cc.vatsim-scandinavia.org/roster/5) as of writing).
2. Click on the filtering dropdown for the "ATC Active" column
3. See that "Visiting Visiting" is shown in the dropdown list

**Expected behavior**
The displayed text should only be "Visiting".

**Screenshots**
![image](https://github.com/user-attachments/assets/a6a8dae3-7efb-46c1-972d-525ac1d6c82b)

**Device and browser (if applicable):**
 - OS: Windows
 - Browser: Firefox
 - Version: 128.0

**Additional context**
I believe the origin is from line 53-54 below, where the non-displayed `<span>` had its html tags stripped for the filtering dropdown via the `tableFilterStripHtml` function and is displayed along with the other "Visiting" in L54.
https://github.com/Vatsim-Scandinavia/controlcenter/blob/b860464f603102a0baecabb7aec60ed50432371f/resources/views/roster.blade.php#L49-L58

https://github.com/Vatsim-Scandinavia/controlcenter/blob/b860464f603102a0baecabb7aec60ed50432371f/resources/views/scripts/global.blade.php#L2-L5

Perhaps changing L53 to the below and deleting L54 would work? The extra space would get trimmed by `tableFilterStripHtml`. I wasn't successful in setting up a dev environment so I could not test it.
```html
<i class="far fa-check-circle"></i> Visiting
```

**Comment by blt950** [comment]
Thanks for the report, I'll fix this so it displays correctly :)
